// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCd8caeaXlUPwH2Ki-VCz1YLdz-hjj5PVs',
    appId: '1:681104665809:web:6f74fb76ca6cb3dbc729f0',
    messagingSenderId: '681104665809',
    projectId: 'lorebook-503208',
    authDomain: 'lorebook-503208.firebaseapp.com',
    storageBucket: 'lorebook-503208.firebasestorage.app',
    measurementId: 'G-3T3478YPF0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBo4tewZYECbfdMokjCHk3kXJ8n6wglUEg',
    appId: '1:681104665809:android:8571fd81fca28e82c729f0',
    messagingSenderId: '681104665809',
    projectId: 'lorebook-503208',
    storageBucket: 'lorebook-503208.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmKbVOD6lkRNi9lE1_-UJ4Sod1nkHolEQ',
    appId: '1:681104665809:ios:f6fd80071fa85050c729f0',
    messagingSenderId: '681104665809',
    projectId: 'lorebook-503208',
    storageBucket: 'lorebook-503208.firebasestorage.app',
    iosBundleId: 'dev.code4soul.lorebook',
  );
}
